#
#server.port=8078
#spring.application.name=apiGateway
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.main.web-application-type=reactive
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#eureka.instance.preferIpAddress=true
#
#management.endpoint.gateway.enabled=true
server:
  port: 8078

spring:
   application:
     name: apiGateway

   main:
       web-application-type: reactive


   cloud:
     gateway:
       routes:
        -  id: LOGINSERVICE
           uri: lb://LOGINSERVICE
           predicates:
             - Path=/arena/**

        -  id: GROUNDSERVICE
           uri: lb://GROUNDSERVICE
           predicates:
             - Path=/api/v1/**

        -  id: BOOKINGSERVICE
           uri: lb://BOOKINGSERVICE
           predicates:
             - Path=/booking/**


        -  id: PAYMENT-SERVICE
           uri: lb://PAYMENT-SERVICE
           predicates:
             - Path=/api/v2/**


        -  id: USERSERVICE
           uri: lb://USERSERVICE
           predicates:
             - Path=/User/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/